### ISSUE TITLE
doe_lcgms

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-data-recipes#4]
https://data.cityofnewyork.us/Education/LCGMS-DOE-School-Information-Report/3bkj-34v2

- [x] load to s3
- [x] build.py 
- [x] *.sql

**Comment by SPTKL** [comment]
- the data set is in xls format, which is not preferred --> communicate with DOE
- the attached csv file has encoding issues and cannot be loaded
- current approach contains manual process

**Comment by AmandaDoyle** [comment]
@SPTKL that's correct that the current approach is a manual process
https://www.nycenet.edu/PublicApps/LCGMS.aspx
^ that is the correct file but I'm having issues opening it
LCGMS_SchoolData(additional geospatial fields added).csv from https://data.cityofnewyork.us/Education/LCGMS-DOE-School-Information-Report/3bkj-34v2
looks like it has all the info and you should just be able to copy the link so that it's no longer a manual process
